[build]
  command = "echo 'Build completo'"
  publish = "."

[build.environment]
  FIREBASE_API_KEY = "AIzaSyCMYqcUU-fOB5nQoU2lBVnJIU_xzsk3eC0"
  FIREBASE_AUTH_DOMAIN = "escala-18337.firebaseapp.com"
  FIREBASE_DATABASE_URL = "https://escala-18337-default-rtdb.firebaseio.com"
  FIREBASE_PROJECT_ID = "escala-18337"
  FIREBASE_STORAGE_BUCKET = "escala-18337.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID = "623332895586"
  FIREBASE_APP_ID = "1:623332895586:web:7070007bc7accfea1fda3b"
  FIREBASE_MEASUREMENT_ID = "G-RLP96MKFRR"
